name: Release Application

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version (e.g., 1.3.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install build

    - name: Build C extension in place
      run: |
        python setup.py build_ext --inplace

    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "*.py" -v

    - name: Build distribution
      run: python -m build

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: Release v${{ github.event.inputs.version }}
        draft: false
        prerelease: false
